version: "3"

services:
  node:
    image: node:12.3-alpine
    command: sh -c "cd /usr/app && npm run run-dev"
    volumes:
      - ./:/usr/app
    ports:
      - "3000:3000"
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"