version: "3"

services:
  node:
    image: matas/mern-stack-node
    ports:
      - "5000:5000"
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"